facts = [
    "The Sun accounts for about 99.86% of the total mass of the Solar System.",
    "A day on Venus is longer than a year on Venus.",
    "Neutron stars are so dense that a teaspoon of their material would weigh about a billion tons on Earth.",
    "The largest volcano in the Solar System is Olympus Mons on Mars, which is nearly three times the height of Mount Everest.",
    "Jupiter's Great Red Spot is a storm that has been raging for at least 400 years.",
    "Saturn could float in water because its average density is less than that of water.",
    "There are more stars in the universe than grains of sand on all of Earth's beaches.",
    "Light from the Sun takes about 8 minutes and 20 seconds to reach Earth.",
    "A year on Mercury is just 88 Earth days long.",
    "The Milky Way galaxy is estimated to contain between 100 and 400 billion stars.",
    "Some stars are so large they could fit millions of Suns inside them.",
    "Black holes warp space and time so intensely that not even light can escape them.",
    "The Andromeda Galaxy is on a collision course with the Milky Way, expected to merge in about 4.5 billion years.",
    "The Moon is slowly drifting away from Earth at a rate of about 3.8 cm per year.",
    "Pluto was reclassified as a dwarf planet in 2006 by the International Astronomical Union.",
    "The Hubble Space Telescope has helped astronomers estimate the age of the universe to be about 13.8 billion years.",
    "Our Solar System orbits the center of the Milky Way Galaxy once every 225 million years.",
    "There are rogue planets drifting through space without orbiting any star.",
    "Some galaxies are over 13 billion years old, nearly as old as the universe itself.",
    "The observable universe is about 93 billion light years across.",
    "Quasars are the brightest objects in the universe, powered by supermassive black holes.",
    "The Sun will eventually expand into a red giant and engulf Mercury, Venus, and possibly Earth.",
    "Stars are born in clouds of gas and dust called nebulae.",
    "A pulsar is a type of neutron star that spins and emits beams of radiation.",
    "Comets are often described as dirty snowballs, made of ice, dust, and rocky material.",
    "The largest moon in the Solar System is Ganymede, a moon of Jupiter.",
    "The Kuiper Belt is a region beyond Neptune filled with icy bodies and dwarf planets.",
    "Oumuamua was the first known interstellar object detected passing through our Solar System.",
    "Dark matter makes up about 27% of the universe, but we still don't know what it is.",
    "Dark energy is believed to be responsible for the accelerated expansion of the universe.",
    "A light-year is about 9.46 trillion kilometers, the distance light travels in one year.",
    "The Sun is a G-type main-sequence star, also called a yellow dwarf.",
    "There are more than 200 moons in the Solar System.",
    "Saturn's moon Titan has lakes and rivers of liquid methane and ethane.",
    "Europa, one of Jupiter's moons, may have a subsurface ocean that could harbor life.",
    "The rings of Saturn are mostly made of ice particles, with some rock and dust.",
    "Meteorites are rocks from space that survive their journey through Earth's atmosphere.",
    "The Oort Cloud is a distant spherical shell of icy objects surrounding the Solar System.",
    "A supernova is the explosive death of a massive star.",
    "Gamma-ray bursts are the most energetic explosions known in the universe.",
    "The largest known star, UY Scuti, is over 1,700 times the radius of the Sun.",
    "The coldest place in the known universe is the Boomerang Nebula, at about -272°C.",
    "The hottest planet in the Solar System is Venus, not Mercury.",
    "Mercury has almost no atmosphere to retain heat, which is why its surface temperatures vary drastically.",
    "There is a black hole at the center of the Milky Way Galaxy called Sagittarius A*.",
    "The James Webb Space Telescope observes the universe in infrared light.",
    "Astronomers have discovered thousands of exoplanets orbiting stars beyond our Sun.",
    "Some exoplanets orbit two stars, much like Tatooine in Star Wars.",
    "The Sun rotates faster at its equator than at its poles.",
    "The Aurora Borealis and Aurora Australis are caused by solar wind interacting with Earth's magnetic field.",
    "The International Space Station orbits Earth about once every 90 minutes.",
    "The fastest rotating planet in our Solar System is Jupiter, completing a rotation in under 10 hours.",
    "Mars has the largest canyon in the Solar System, Valles Marineris, stretching over 4,000 km.",
    "The surface of the Sun is about 5,500°C, but its core reaches 15 million°C.",
    "White dwarfs are the remnants of stars that have exhausted their fuel.",
    "A black hole's boundary beyond which nothing can escape is called the event horizon.",
    "Some galaxies have supermassive black holes billions of times the mass of the Sun.",
    "Globular clusters are dense collections of tens of thousands of stars.",
    "Binary star systems are common, with two stars orbiting each other.",
    "Cosmic microwave background radiation is the afterglow of the Big Bang.",
    "The universe is expanding, and galaxies are moving away from each other.",
    "The speed of light is about 299,792 kilometers per second.",
    "Saturn's moon Enceladus has geysers that shoot water vapor into space.",
    "Astronauts in orbit experience microgravity, making them appear weightless.",
    "The planet Uranus rotates on its side, tilted by about 98 degrees.",
    "Neptune's winds are the fastest in the Solar System, reaching up to 2,100 km/h.",
    "The Sun will eventually become a white dwarf after shedding its outer layers.",
    "Cosmic rays are high-energy particles from space that strike Earth.",
    "Some stars end their lives as black holes, others as neutron stars, and smaller ones as white dwarfs.",
    "Dwarf galaxies are much smaller than spiral or elliptical galaxies but are abundant in the universe.",
    "Redshift is used by astronomers to measure the distance and speed of receding galaxies.",
    "The largest known structure in the universe is the Hercules Corona Borealis Great Wall, a massive galactic filament.",
    "Some stars called hypergiants are millions of times brighter than the Sun.",
    "The North Star, Polaris, is not the brightest star in the sky; Sirius holds that title.",
    "A solar eclipse occurs when the Moon passes between the Sun and Earth.",
    "A lunar eclipse happens when Earth blocks sunlight from reaching the Moon.",
    "The far side of the Moon is often mistakenly called the 'dark side,' but it receives sunlight too.",
    "Space is not completely empty; it contains gas, dust, and cosmic rays.",
    "The Sun's magnetic activity causes sunspots, solar flares, and coronal mass ejections.",
    "Jupiter emits more energy than it receives from the Sun due to its internal heat.",
    "Neutron stars can spin hundreds of times per second.",
    "The Drake Equation estimates the number of advanced civilizations in our galaxy.",
    "The Fermi Paradox questions why we haven't detected extraterrestrial life despite the vastness of the universe.",
    "The Hubble Deep Field image revealed thousands of galaxies in a tiny patch of sky.",
    "Infrared telescopes can see through cosmic dust clouds that block visible light.",
    "Earth is the only known planet with liquid water on its surface.",
    "A black dwarf is a theoretical end stage of a white dwarf when it has cooled completely.",
    "Asteroids are rocky bodies mostly found in the asteroid belt between Mars and Jupiter.",
    "Ceres is the largest object in the asteroid belt and classified as a dwarf planet.",
    "The Kuiper Belt object Eris is slightly smaller than Pluto but more massive.",
    "The largest known galaxy is IC 1101, over 6 million light years in diameter.",
    "Time moves slower in stronger gravitational fields, as predicted by general relativity.",
    "The Sun's corona is hotter than its surface, a mystery still studied by scientists."
]
