facts = [
    "A day on Venus is longer than a year on Venus.",
    "Neutron stars can spin 600 times per second.",
    "Jupiter has 95 moons orbiting it.",
    "Light from the Sun takes 8 minutes to reach Earth.",
    "There are more stars in the universe than grains of sand on Earth.",
    "Saturn could float in water because it's mostly gas.",
    "Black holes can warp time and space.",
    "Mars has the largest volcano in the solar system — Olympus Mons.",
    "A day on Venus is longer than a year on Venus.",
    "Neutron stars can spin at a rate of 600 rotations per second.",
    "There may be a planet made out of diamonds twice the size of Earth.",
    "A teaspoon of a neutron star weighs about 6 billion tons.",
    "There are more trees on Earth than stars in the Milky Way.",
    "Saturn could float in water because it is mostly made of gas.",
    "One million Earths could fit inside the Sun.",
    "The footprints on the Moon will last for millions of years.",
    "There's a giant cloud of alcohol in space.",
    "The largest volcano in the Solar System is on Mars, called Olympus Mons.",
    "The coldest place in the universe is the Boomerang Nebula.",
    "Jupiters Great Red Spot has been raging for at least 350 years.",
    "Pluto has mountains made of ice.",
    "There are more stars in the universe than grains of sand on Earth.",
    "A year on Mercury is just 88 Earth days.",
    "The Sun accounts for 99.86% of the mass in the Solar System.",
    "Astronauts grow taller in space because of reduced gravity.",
    "A day on Jupiter lasts less than 10 hours.",
    "Uranus rotates on its side, making its seasons extreme.",
    "Mars has the largest dust storms in the Solar System.",
    "Light from the Sun takes about 8 minutes to reach Earth.",
    "The Milky Way galaxy is on a collision course with the Andromeda galaxy.",
    "Black holes can slow down time around them.",
    "If two pieces of the same type of metal touch in space, they bond permanently (cold welding).",
    "Venus is the hottest planet in the Solar System, not Mercury.",
    "Space is completely silent since sound cannot travel in a vacuum.",
    "Saturn has over 140 moons and moonlets.",
    "Astronauts can't burp properly in space due to lack of gravity.",
    "A day on Neptune lasts about 16 hours.",
    "There is a planet, HD 189733b, where it rains glass sideways.",
    "Some stars are so big they could fit our entire Solar System inside them.",
    "Halley's Comet only passes Earth once every 76 years.",
    "The Sun is about halfway through its 10-billion-year life cycle.",
    "Mercury has no atmosphere to retain heat, so temperatures swing wildly.",
    "Jupiter is so massive it could fit all other planets inside it.",
    "Saturn's rings are mostly water ice mixed with dust.",
    "Mars has two tiny moons, Phobos and Deimos.",
    "Neptune has the fastest winds in the Solar System, up to 2,100 km/h.",
    "The International Space Station travels at 28,000 km/h.",
    "Light from the nearest star (Proxima Centauri) takes 4.2 years to reach us.",
    "Some galaxies are over 13 billion years old.",
    "Our galaxy, the Milky Way, is 100,000 light-years across.",
    "There are rogue planets that drift through space without stars.",
    "Astronauts' suits cost around $12 million each.",
    "The universe is expanding faster than the speed of light.",
    "The Hubble Space Telescope can see galaxies billions of light-years away.",
    "The Moon is drifting away from Earth by about 3.8 cm per year.",
    "Earth's rotation is gradually slowing down.",
    "The James Webb Space Telescope can look 13.5 billion years into the past.",
    "The farthest galaxy ever observed is more than 32 billion light-years away.",
    "Dark matter makes up about 27% of the universe, but we can't see it.",
]